#!/bin/env bash

# Create a data URL from a file
function dataurl() {
	local mimeType=$(file -b --mime-type "$1");
	[[ $mimeType = text/* ]] && mimeType="${mimeType};charset=utf-8"
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

# EOF dataurl
