#!/bin/sh

# Show 256 TERM colors
function colors()
{
  local X=$(tput op)
  local Y=$(printf %$((COLUMNS-6))s)
  local i=
  for i in {0..256}; do
    o=00$i;
    echo -e ${o:${#o}-3:3} $(tput setaf $i;tput setab $i)${Y// /=}$X;
  done  
}

# EOF colors
