#!/bin/sh

# Create a data URL from a file
function dataurl() {
    local MIMETYPE=$(file --mime-type "$1" | cut -d ' ' -f2)
    [[ $MIMETYPE = "text/*" ]] && MIMETYPE="${MIMETYPE};charset=utf-8"
    echo "data:${MIMETYPE};base64,$(openssl base64 -in "$1" | tr -d '\n')"
}

# EOF dataurl
