#!/bin/sh

# Get gzipped file size
function gz() {
    local ORIGSIZE=$(wc -c < "$1")
    local GZIPSIZE=$(gzip -c "$1" | wc -c)
    local RATIO=$(echo "$GZIPSIZE * 100/ $ORIGSIZE" | bc -l)
    local SAVED=$(echo "($ORIGSIZE - $GZIPSIZE) * 100/ $ORIGSIZE" | bc -l)
    printf "orig: %d bytes\ngzip: %d bytes\nsave: %2.0f%% (%2.0f%%)\n" "$ORIGSIZE" "$GZIPSIZE" "$SAVED" "$RATIO"
}

# EOF gz
