#!/bin/sh

function is-supported() {
    if [ $# -eq 1 ]; then
        eval "$1" > /dev/null 2>&1
    else
        eval "$1" > /dev/null 2>&1 && echo -n "$2" || echo -n "$3"
    fi
}

# EOF is-supported
