#!/bin/sh

# Add to path
function prepend-to-path() {
  local path_var="$1"							# the name of the PATH variable (such as "PATH")
  local to_add="$2"								# the directory to add the to given PATH variable
  if [ -d "$to_add" ]; then						# if directory to add exists
    local cur_path=$(eval echo -n "\$$1")		# evaluate the current contents of the variable
    eval "$path_var='${to_add}:${cur_path}'"	# add it
  fi
}

# EOF prepend-to-path
