#!/bin/env bash
# Autoincluded by .bash_profile (TODO: review this file)

# Useful git functions are defined each in their own file under ./fun/

for funfile in fun/*; do
  # skips all files named with all caps so README's are not included :)
  [[ $funfile =~ ^[A-Z]*$ ]] || \
  case "$funfile" in 
    *~)		;;
    *.bak)	;;
    *.txt)	;;
	*.sh)	;;
    *)
	  [ -f "$funfile" ] && [ -r "$funfile" ] && echo "Attempting to source $funfile" && pushd fun && . "$funfile" && popd ;;
  esac
done
unset funfile

# EOF
