#!/bin/env bash
# Autoincluded by .bash_profile (TODO: review this file)

# Change this to 
#SYSFUN=quiet
#SYSFUN=basic
SYSFUN=verbose

${SYSFUN}-file-entry $BASH_SOURCE "system/" "
  system/function provides: $(cd fun; ls | grep -v '^[A-Z]*$')"

#for f in *; do expr $f : "^[A-Z]*$" > /dev/null || echo $f;  done
# Useful bash functions are defined each in their own file under ./fun/
pushd fun
for funfile in *; do
  # skips all files named with all caps so README's are not included :)
  [[ $funfile =~ ^[A-Z]*$ ]] || \
  case "$funfile" in 
    *~)		;;
    *.bak)	;;
    *.txt)	;;
	*.sh)	;;
    *)
	  [ -f "$funfile" ] && [ -r "$funfile" ] && echo "Attempting to source $funfile" && . "$funfile" ;;
  esac
done
unset funfile
popd


${SYSFUN}-file-exit $BASH_SOURCE "system/"

# EOF
